
public class ObjCons3 {

    public static void main(String[] args) {
        Student s1 = new Student("Shivam", 22, 5.10);
        s1.display();

        Student s2 = new Student("Rahul");
        s2.display();

        Student s3 = new Student();
        s3.display();

    }
}

class Student {

    String name;
    int age;
    double height;

    // Default Parameterized is generated by compiler when there is no constructor is written explicitly
    // No Parameterized Constructor
    Student() {
        name = null;
        age = 0;
        height = 0.0;
    }

    // 1 Parametrized Constructor
    Student(String name) {
        this.name = name;
    }

    // Parametrized Constructor
    Student(String name, int age, double height) {
        this.name = name;
        this.age = age;
        this.height = height;
    }

    void display() {
        System.out.println("Name: " + name);
        System.out.println("Age: " + age);
        System.out.println("Height: " + height);
    }
}
